#!/bin/bash
# Exit immediately if a command exits with a non-zero status.
set -e

sudo systemctl disable systemd-networkd-wait-online.service
sudo apt update && sudo apt upgrade -y
sudo apt install ubuntu-desktop -y
sudo apt update && apt install spice-vdagent spice-webdavd -y



# Create the install_ros.sh file to run after logging in to ubuntu desktop
FILE_PATH="install_ros.sh"
AUTHOR="Daniel Houghton"
DATE=$(date +%Y-%m-%d)

cat << EOF > "$FILE_PATH"
#!/bin/bash
# -----------------------------------
# Ubuntu Installation Part 2
# and
# ROS2 Installation
# Generated by: $AUTHOR
# Date: $DATE
# -----------------------------------
#Start of Installation Script

# Exit immediately if a command exits with a non-zero status.
set -e

gsettings set org.gnome.desktop.peripherals.mouse natural-scroll true

echo 'export BROWSER="/usr/bin/firefox"' >> ~/.bashrc
source ~/.bashrc

sudo apt update
sudo apt install wget gpg -y
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
sudo install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
echo 'deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main' | sudo tee /etc/apt/sources.list.d/vscode.list
rm packages.microsoft.gpg

sudo apt update
sudo apt install code -y
gsettings set org.gnome.desktop.peripherals.mouse natural-scroll true
sudo apt purge libreoffice* thunderbird* rhythmbox* shotwell* totem* -y
sudo apt autoremove -y
rm -r Documents Downloads Music Pictures Public Templates Videos

sudo apt install gh -y
gh auth login
gh repo clone daniel-houghton/scara

echo "--- 1. Setting Locale ---"
locale  # check for UTF-8

sudo apt update && sudo apt install locales
sudo locale-gen en_US en_US.UTF-8
sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
export LANG=en_US.UTF-8

locale  # verify settings



echo "--- 1.A Adding Universe ---"
sudo apt install software-properties-common -y
sudo add-apt-repository universe



echo "--- 2 Installing the ros2-apt-source package ---"
sudo apt update && sudo apt install curl -y
export ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F\" '{print $4}')
curl -L -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.$(. /etc/os-release && echo ${UBUNTU_CODENAME:-${VERSION_CODENAME}})_all.deb"
sudo dpkg -i /tmp/ros2-apt-source.deb



echo "--- 3. Installing ROS 2 ---"
# Install development tools
sudo apt update && sudo apt install -y ros-dev-tools

sudo apt update
sudo apt upgrade
sudo apt install -y ros-kilted-desktop

echo "--- 4. Setting up Environment ---"
# Add the sourcing command to .bashrc if it's not already there
ROS_SETUP_LINE="export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
source /opt/ros/kilted/setup.bash
source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash
export ROS_DOMAIN_ID=0
source ~/scara/install/setup.bash
export QT_QPA_PLATFORM=xcb
"
echo "$ROS_SETUP_LINE" >> ~/.bashrc
echo "Added ROS 2 sourcing to .bashrc"


# Optional: Source for the current shell
source /opt/ros/kilted/setup.bash

echo "--- ROS2 Desktop Installation Complete! ---"
source ~/.bashrc

echo "---  Installing CycloneDDS ---"
sudo apt update
sudo apt install ros-$ROS_DISTRO-rmw-cyclonedds-cpp -y
source ~/.bashrc


# echo "---  Installing MoveIt ---"
# sudo apt update
# sudo apt install ros-$ROS_DISTRO-moveit -y
# source ~/.bashrc

echo "---  Installing ros2_control ---"
sudo apt update
sudo apt install ros-$ROS_DISTRO-ros2-control ros-$ROS_DISTRO-ros2-controllers -y
source ~/.bashrc

# End of Installation Script
EOF

chmod +x $FILE_PATH
echo "Successfully created $FILE_PATH"

sudo reboot
